# Generated by Django 2.2.19 on 2021-06-24 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210624_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='down_votes_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='up_votes_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
