# Generated by Django 2.2.19 on 2021-05-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210530_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='photo',
        ),
    ]
