# Generated by Django 2.2.19 on 2021-06-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('classroom', '0003_auto_20210530_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded')], default='Pending', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classroom.Course')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignment.Submission')),
            ],
        ),
    ]
